# Auto-generated by nixlycc — Control Panel → Mouse & Keyboard.
{ lib, pkgs, ... }:

{
  services.xserver.xkb.layout = lib.mkForce "no";
  services.xserver.xkb.variant = lib.mkForce "";
  console.keyMap = lib.mkForce "no";

  # Read by nixlytile, which re-applies it to every pointer and keyboard as
  # soon as the file changes — a switch takes effect without logging out.
  environment.etc."nixlyos/input.conf".text = ''
    accel-profile=adaptive
    accel-speed=0.00
    natural-scroll=false
    left-handed=false
    middle-button-emulation=false
    scroll-method=wheel
    button-map=lrm
    keyboard-layout=no
    keyboard-variant=
    repeat-delay=300
    repeat-rate=100
  '';
  services.hardware.openrgb.enable = true;

  systemd.services.nixly-input-hardware = {
    description = "Apply nixlycc mouse and keyboard hardware settings";
    wantedBy = [ "multi-user.target" ];
    after = [ "openrgb.service" ];
    path = with pkgs; [ openrgb ];
    serviceConfig.Type = "oneshot";
    script = ''
      openrgb --noautoconnect --mode rainbow --color 00beff --brightness 100 || true
    '';
  };
}
