# Auto-generated by nixlycc — Control Panel → Applications.
{ ... }:

{
  config.home-manager.sharedModules = [
    ({ pkgs, pkgs-unstable, ... }: {
      home.packages =
        (with pkgs; [
          brave
          citrix-workspace-nixly
          claude
          discord
          google-chrome
          nixlymedia
          onlyoffice-desktopeditors
          pavucontrol
          spotify
          teams-for-linux
          vlc
        ])
        ++ (with pkgs-unstable; [
        ]);
    })
  ];
}
