# Auto-generated by nixlycc — Control Panel → Applications.
# The availableOn filter drops packages the platform cannot run (x86-only
# binaries like Discord/Chrome on an ARM SBC) instead of failing the eval;
# nixlycc must keep this filter when regenerating the file.
{ lib, ... }:

{
  config.home-manager.sharedModules = [
    ({ pkgs, pkgs-unstable, ... }: {
      home.packages = builtins.filter
        (lib.meta.availableOn pkgs.stdenv.hostPlatform)
        ((with pkgs; [
          brave
          citrix-workspace-nixly
          claude
          discord
          google-chrome
          nixlymedia
          onlyoffice-desktopeditors
          pavucontrol
          spotify
          teams-for-linux
          vlc
        ])
        ++ (with pkgs-unstable; [
        ]));
    })
  ];
}
