{ pkgs, hwData, osConfig ? null, ... }:

let
  # Generated by scripts/detect-hw.sh; an empty string means no NVIDIA GPU.
  hasNvidia = hwData.detected.nvidia != "";

  # HTPC boots straight into Steam Big Picture with a minimal autostart
  # list; the desktop autostarts below stay exactly as before.
  isHtpc = osConfig != null && osConfig.nixlyos.mode == "htpc";

  # Picks the widest connected output instead of a hardcoded connector:
  # a monitor moved to another port renames the connector (DP-1 -> DP-2),
  # and a stale name silently left Xwayland without a RandR primary.
  setRandrPrimary = pkgs.writeShellScript "nixly-xrandr-primary" ''
    export DISPLAY=:0
    for _ in $(seq 10); do
      out=$(${pkgs.xorg.xrandr}/bin/xrandr 2>/dev/null \
        | sed -n 's/^\([^ ]*\) connected.* \([0-9]\+\)x[0-9]\++.*/\2 \1/p' \
        | sort -rn | head -1 | cut -d' ' -f2)
      if [ -n "$out" ] && ${pkgs.xorg.xrandr}/bin/xrandr --output "$out" --primary 2>/dev/null; then
        exit 0
      fi
      sleep 1
    done
  '';
in
{
  imports = [
    ./clipman.nix
    ./nautilus.nix
  ];

  home.packages = with pkgs; [
    grim
    slurp
    wl-clipboard
    libnotify
    sway-contrib.grimshot
    swappy
    swaybg
    clipman
    fuzzel
    kdePackages.breeze-icons
    kdePackages.qtwayland
    samba
    cifs-utils
    foot
    brightnessctl
    playerctl
    wireplumber
    xwayland-satellite
    xrandr
    socat
    jq
    nixly_launcher
  ];
  # mcontrolcenter is installed system-wide in hardware/msi-ec.nix; the GUI
  # autostarts from config.kdl below, the only mechanism that works here.

  home.file."Pictures/wallpapers/beach.jpg".source = ../wallpapers/beach.jpg;

  xdg.configFile."nixlytile/config.kdl".text = ''
    // nixlytile config (managed by home-manager: home/nixlytile.nix).
    // Keybindings are NOT here: nixlytile reads and inotify-watches
    // ~/.local/nixlyos/bindings.conf directly, so binding edits apply
    // immediately without a rebuild.
    // Hot-reload of this file: pkill -USR1 nixlytile

    appearance {
        gaps 4
        border-px 1
        smartgaps           false
        sloppy-focus        true
        bypass-surface-visibility false
        gaps-enabled        true
        root-color          "#222222ff"
        border-color        "#595959ff"
        focus-color         "#00beffff"
        urgent-color        "#ff0000ff"
        fullscreen-bg       "#1a1a1aff"
        resize-factor       0.0002
        resize-interval-ms  8
        resize-min-pixels   1.0
        resize-ratio-epsilon 0.001
        lock-cursor         false
    }

    input {
        keyboard {
            layout       "no"
            repeat-delay 300
            repeat-rate  100
        }
        touchpad {
            tap                     true
            tap-and-drag            true
            drag-lock               true
            natural-scroll          true
            disable-while-typing    true
            left-handed             false
            middle-button-emulation false
            scroll-method   "2fg"
            click-method    "button-areas"
            send-events     "enabled"
            accel-profile   "adaptive"
            accel-speed     0.0
            button-map      "lrm"
        }
    }

    // Unreal Editor deler app-id mellom prosjektvelgeren og selve editoren,
    // saa reglene skiller paa tittel.  Velger- og opprett-vinduene er dialoger
    // som ikke hoerer hjemme flislagt over hele skjermen; editoren selv
    // (tittel "<Prosjekt> - Unreal Editor") skal fortsatt flislegges.
    window-rule {
        app-id   "UnrealEditor"
        title    "Unreal Engine 5"
        floating true
    }
    window-rule {
        app-id   "UnrealEditor"
        title    "New Project"
        floating true
    }
    window-rule {
        app-id   "UnrealEditor"
        title    "Create Project"
        floating true
    }

    // Citrix Workspace: sesjonsvinduet fyller skjermen naar sesjonsopploesningen
    // matcher monitoren, og skal ikke faa game-behandling eller lov til aa
    // fullskjerme seg selv.
    window-rule {
        app-id     "Wfica"
        game       false
        fullscreen false
    }

    modkey      "Super"
    monitorkey  "Ctrl"

    // Multi-monitor gaming: oppløsningen spillet velger avgjør.
    // Normal oppløsning (≤ skjermen) = 1 skjerm som før. Velger spillet
    // en surround-oppløsning som er bredere/høyere enn skjermen (f.eks.
    // 5760x1080 på 3x1080p) spennes det automatisk over alle aktive
    // skjermer, og musen kan bevege seg over hele flaten.
    // Super+Shift+M tvinger span på for spill som ikke kan be om større
    // oppløsning selv (trykk igjen for å gå tilbake til auto).
    // "off" = aldri automatisk span.
    game-span "auto"

    ${pkgs.lib.optionalString hasNvidia ''
    // Late-latch (utsett game-commit til rett foer vblank) er av paa
    // NVIDIA: driveren avviser IN_FENCE_FD (EPERM) paa 555+, saa
    // wlroots-workarounden venter ut fencen CPU-side INNE i commiten.
    // Latch-budsjettet (maks 10 ms) dekker ikke en vent som varer til
    // spillets GPU-arbeid er ferdig — commiten bommer paa vblank og
    // hvert spill jitrer konstant. Immediate-path gir fencen nesten en
    // hel refresh aa signalere paa i stedet.
    game-late-latch false
    ''}
    wallpaper "~/Pictures/wallpapers/beach.jpg"

    // "info" i produksjon — debug betyr per-event formatering + logg-IO
    // i frame-pathen.  Sett "debug" midlertidig ved feilsøking.
    log-level "info"

    ${if isHtpc then ''
    // HTPC-modus i kompositoren: statusbar alltid skjult, faste
    // app-workspaces (reglene under), gamepad hold-L1/R1 1,5 s for aa
    // skli mellom workspaces, ingen workspace-komprimering.
    htpc true

    // Fast workspace per app. Appene under mappes SKJULT inn paa sitt
    // workspace naar det ikke er aktivt — de stjeler aldri fokus og
    // dukker aldri opp paa et annet workspace. "steam" matcher ogsaa
    // steamwebhelper (guide-menyen) og steam_app_* (spill), saa alt
    // Steam-relatert holder seg paa workspace 1.
    window-rule {
        app-id    "steam"
        workspace 1
    }
    window-rule {
        app-id    "retroarch"
        workspace 2
    }
    window-rule {
        app-id    "RetroArch"
        workspace 2
    }
    // Flatpak-Electron rapporterer app-id ulikt mellom versjoner —
    // begge stavemaater dekkes (regel-match er substring, case-sensitiv).
    window-rule {
        app-id    "geforcenow"
        workspace 3
    }
    window-rule {
        app-id    "GeForce NOW"
        workspace 3
    }
    window-rule {
        app-id    "nixlymedia"
        workspace 4
    }

    // HTPC autostart: Steam Big Picture (ws 1) + RetroArch (ws 2) +
    // GeForce NOW (ws 3) + nixlymedia (ws 4). Alle fire holdes i live
    // av hver sin supervisor-loekke (session.nix / workspace-apps.nix):
    // krasjer en app startes den umiddelbart paa nytt og window-rule
    // legger den rett tilbake paa sitt workspace.
    autostart "swaybg -i \"$HOME/Pictures/wallpapers/beach.jpg\" -m fill"
    // Steam er en X11-klient — xwayland-satellite maa opp foerst.
    autostart "xwayland-satellite"
    autostart "${setRandrPrimary}"
    // Rett i Big Picture; htpc-steam rydder bort gamle snarveier
    // (appene har egne workspaces) og holder Steam i live hele sesjonen.
    autostart "htpc-steam"
    autostart "htpc-retroarch"
    autostart "htpc-geforcenow"
    autostart "htpc-nixlymedia"
    '' else ''
    // Autostart — one process per entry.
    // thunar --daemon fjernet: Nautilus er filbehandleren (Super+e), og
    // thunar-daemonen dro med seg 5 residente gvfs-volume-monitors
    // (goa/gphoto2/afc/mtp/udisks) ved hver innlogging. Thunar starter
    // fortsatt on-demand om noe kaller den.
    autostart "swaybg -i \"$HOME/Pictures/wallpapers/beach.jpg\" -m fill"
    // nm-applet/blueman-applet fjernet: nettverk + bluetooth er innebygd
    // i nixlytile (egne tray-ikoner med popup, direkte mot kernel/bluez).
    autostart "xwayland-satellite"
    // Uten RandR-primary regner Wine/UE4 første monitor (HDMI, 1080p) som
    // primær display-enhet, så exclusive fullscreen bare tilbyr 1080p-moduser.
    // Retry-løkke fordi Xwayland-satellite trenger et par sekunder på å komme opp.
    autostart "${setRandrPrimary}"
    autostart "sh -c 'wl-paste --type text --watch clipman store --no-persist'"
    autostart "sh -c 'wl-paste --primary --type text --watch clipman store --no-persist'"
    // Prewarm KUN naar Steam allerede kjoerer (startes aldri herfra) OG
    // musen har vaert inaktiv i 10 min; avbrytes straks musen roerer seg.
    // Varmer KUN de to sist spilte spillene (se prewarm.nix). Service-
    // gaten nekter fortsatt aa kjoere naar gametune/gamemoded melder
    // aktivt spill eller maskinen er travel.
    autostart "nixly-activity-prewarm"
    // appd walker HELE $HOME ved oppstart (fileindex + gitscan) og bygger
    // et ikon-indeks paa ~21k entries. Rett etter innlogging konkurrerer
    // det med kompositoren om CPU og disk, og musen fryser 2-3s. Utsatt
    // 8s (kompositor + Wayland-klienter er oppe da) og nice 19 saa
    // indekseringen aldri preempter frame-pathen. Super+p virker fra ~8s.
    autostart "sh -c 'sleep 8; exec nice -n 19 appd'"
    // Steam startes ALDRI automatisk — hverken ved innlogging eller av
    // nixly-activity-prewarm. Brukeren starter den selv.
    autostart "mcontrolcenter"
    ''}
  '';
}
