{ config, lib, pkgs, hwData, ... }:

let
  # Decimal PCI addresses generated by scripts/detect-hw.sh.
  gpu = hwData.detected;
in
{
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      vulkan-loader
      libGL
      libglvnd
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      vulkan-loader
      libGL
      libglvnd
    ];
  };

  hardware.nvidia = {
    modesetting.enable = true;
    # Persistenced keeps the dGPU initialized (awake) at all times — the main
    # idle drain. Off, so the driver can drop the GPU when nothing uses it.
    nvidiaPersistenced = false;
    # Save/restore dGPU state across S3 so a closed lid actually sleeps it.
    powerManagement.enable = true;
    # Fully power the dGPU off (D3cold, ~0 W) whenever no offload client is
    # running — always, on battery. Intel drives the panel (PRIME offload
    # below), so the dGPU has no outputs and can suspend. Games that need it
    # get it via set_dgpu_env()/nvidia-offload and wake it (~200 ms first use).
    powerManagement.finegrained = true;
    open = false;
    nvidiaSettings = false;
    # `cachyos` is chaotic-nyx's prebuilt driver matched to the CachyOS kernel;
    # any other kernel falls back to building `latest` locally.
    package = lib.mkDefault (
      config.boot.kernelPackages.nvidiaPackages.cachyos
        or config.boot.kernelPackages.nvidiaPackages.latest
    );

    # nvidia-powerd pins the GPU ceiling at its 10 W floor here, so the driver's
    # static 80 W default is better.
    dynamicBoost.enable = false;

    # GSP enforces the SBIOS power clamp; disabling it moves arbitration to the driver.
    gsp.enable = false;

    # Offload, not reverseSync: Intel drives the only connected panel, and forcing
    # Nvidia primary made the panel an mgpu secondary whose swapchain alloc failed.
    prime = {
      offload.enable = true;
      offload.enableOffloadCmd = true;
      intelBusId = gpu.intel;
      nvidiaBusId = gpu.nvidia;
    };
  };

  boot = {
    initrd.kernelModules = [ "nvidia" "nvidia_uvm" "nvidia_modeset" "nvidia_drm" ];
    # Cmdline, not extraModprobeConfig: the nvidia modules load in the initrd.
    kernelParams = [
      "nvidia_drm.modeset=1"
      "nvidia_drm.fbdev=1"
      # PAT for GPU mappings, faster CPU-to-GPU uploads.
      "nvidia.NVreg_UsePageAttributeTable=1"
      # Skip zeroing new GPU memory; accepted on a single-user desktop.
      "nvidia.NVreg_InitializeSystemMemoryAllocations=0"
      # No-op on Turing, correct if the GPU is ever swapped.
      "nvidia.NVreg_EnableResizableBar=1"
    ];
  };

  environment.systemPackages = with pkgs; [
    vulkan-tools
    libva-utils
    nvtopPackages.full
    egl-wayland
    nvidia-vaapi-driver
  ];

  # No global GBM_BACKEND/__GLX_VENDOR_LIBRARY_NAME: that black-screens the Intel
  # primary output, and games get the Nvidia env per-process from set_dgpu_env().

  environment.sessionVariables = {
    __GL_VRR_ALLOWED = "1";
    __GL_GSYNC_ALLOWED = "1";
    __GL_THREADED_OPTIMIZATIONS = "1";
    __GL_SHADER_DISK_CACHE = "1";
    __GL_SHADER_DISK_CACHE_SIZE = "10737418240";   # 10 GiB shader cache
    # Never trim the cache mid-session; eviction shows up as recompile hitches.
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP = "1";
    MESA_SHADER_CACHE_MAX_SIZE = "10G";
    # No global WLR_RENDERER: the nixlytile wrapper exports vulkan itself.
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
  };
}
