# Prebuilt proton-nixlyos Steam compatibility tool: Valve bleeding-edge
# Proton + wine with the CachyOS fork changes, built by
# github:aCeTotal/proton-nixlyos and published as a GitHub release.
# pin.json is regenerated by that repo's scripts/publish.sh.
{ lib, stdenvNoCC, fetchurl, variant ? "v3" }:

let
  pin = lib.importJSON ./pin.json;
  release = pin.variants.${variant} or (throw
    "proton-nixlyos: variant '${variant}' not in pin.json - publish it with scripts/publish.sh in the proton-nixlyos repo");
in
stdenvNoCC.mkDerivation {
  pname = "proton-nixlyos-${variant}";
  version = pin.version;

  src = fetchurl {
    url = release.url;
    hash = release.hash;
  };

  sourceRoot = "proton-nixlyos";

  dontConfigure = true;
  dontBuild = true;
  # Prebuilt Steam Runtime binaries; never strip or patchelf them.
  dontFixup = true;

  # Steam scans the subdirectories of each entry in
  # STEAM_EXTRA_COMPAT_TOOLS_PATHS, so the tool root goes in $out/bin
  # (same layout as chaotic-nyx's proton-cachyos, which
  # modules/core/steam/autoconfig.nix in .nixlyos also relies on).
  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -a . $out/bin/
    runHook postInstall
  '';

  meta = {
    description = "Proton build from Valve bleeding-edge with CachyOS fork patches (proton-nixlyos)";
    homepage = "https://github.com/aCeTotal/proton-nixlyos";
    license = lib.licenses.bsd3;
    platforms = [ "x86_64-linux" ];
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
